[build]
  publish = "."
  command = "echo 'Site estático'"

[build.environment]
  NODE_VERSION = "18"

# Headers para performance e cache busting
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Cache-Buster = "v2025-09-10-enhanced"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Configurações de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuração para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/emergency.html"
  status = 404
  status = 404
