[build]
  # Diretório de publicação (raiz do projeto)
  publish = "."
  
  # Comando de build (não necessário para site estático)
  command = "echo 'Site estático - sem build necessário'"

[build.environment]
  NODE_VERSION = "18"

# Configurações de redirecionamento
[[redirects]]
  from = "/index"
  to = "/portal_aprendizado.html"
  status = 301

[[redirects]]
  from = "/"
  to = "/portal_aprendizado.html"
  status = 200

# Headers para melhor performance
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Configurações de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuração para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/portal_aprendizado.html"
  status = 404
